% Created by Janelyn Anderson (student) without any help
% November 2023

% clear workspace and load data needed for code generation
clear all
evalin('base', 'Odometry_data');

% XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
% --- --- --- --- --- --- --Write to file-- --- --- --- --- --- --- --- ---
% XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
% Created by Janelyn Anderson (student) without any help
% November 2023

CPPFileID = fopen('..\src\main\cpp\SimulinkNetworkTables2.cpp', 'w');
HFileID = fopen('..\src\main\include\SimulinkNetworkTables2.h', 'w');
if CPPFileID == -1
    error('Could not open .cpp file for writing');
end
if HFileID == -1
    error('Could not open .h file for writing');
end

% H File
HFileContents = {...
    '// This file has been auto generated from a Matlab script',...
    '// Do not manually edit since changes will be lost',...
    '#include <frc/smartdashboard/SmartDashboard.h>',...
    '#include <networktables/NetworkTable.h>',...
    '#include <networktables/RawTopic.h>',...
    '#include <networktables/NetworkTableInstance.h>',...
    '#include "Odometry_ert_rtw\Odometry.h"',...
    '#include "DertLib/include/Component.h"',...
    ' ',...
    'class SimulinkNetworkTables2 : public dlib::Component',...
    '{',...
    '    public:',...
    '        void PreStepCallback() override;',...
    '        void PostStepCallback() override;',...
    '    private:',...
    '};'
    };

% CPP File
CPPFileContents = {...
    '// This file has been auto generated from a Matlab script',...
    '// Do not manually edit since changes will be lost',...
    '#include "include/SimulinkNetworkTables2.h"',...
    ' ',...
    'void SimulinkNetworkTables2::PreStepCallback() {}',...
    'void SimulinkNetworkTables2::PostStepCallback() {}',...
    };

% make file contents
for i = 1:length(CPPFileContents)
    fprintf(CPPFileID, '%s\n', CPPFileContents{i});
end

for i = 1:length(HFileContents)
    fprintf(HFileID, '%s\n', HFileContents{i});
end

% Close the files
fclose(CPPFileID);
fclose(HFileID);

clear HFileID HFileContents CPPFileID CPPFileContents

% XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
% --- --- --- --- --- --- --- --Build Code-- --- --- --- --- --- --- --- --
% XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

generate_code_Odometry;